package bg.bulsi.egov.eauth.eid.provider.model;


public enum AttributeMapKeys {
	//First Name
	BIRTH_FIRST_NAME, 
	CURRENT_FIRST_NAME,
	LATIN_CURRENT_FIRST_NAME,
	//Family
	BIRTH_FAMILY_NAME, 
	CURRENT_FAMILY_NAME,
	LATIN_CURRENT_FAMILY_NAME, 
	//Attribute
	LATIN_NAME,
	PERSON_IDENTIFIER,
	PERSON_NAME,
	EMAIL,
	PHONE,
	BIRTH_NAME,
	DATE_OF_BIRTH,
	GENDER,
	PLACE_OF_BIRTH,
	CURRENT_ADDRESS_STRUCTURED,
	PASSWORD
}
