############ ACTUATOR ############

spring:
#   autoconfigure:
#      exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
   profiles:
      include: actuator-ext #, audit
   #Actuator credentiials
   security:
      user:
         name: 'actuator'
         password: 'actuatorpassword'


#management.endpoint.<id>.enabled#
management:
   endpoints:
      enabled-by-default: true
      web.exposure:
         include: '*'
         exclude: beans #, health, info
   endpoint:
      health:
         enabled: true
         show-components: always  #when-authorized, always, never
         show-details: always #when-authorized, always, never
      info.enabled: true
      shutdown.enabled: false
      auditevents.enabled: true
info:
   app:
      description: Eauth UI backend
#                                 #
###################################