//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 06:03:16 PM EEST 
//


package bg.bulsi.egov.saml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClaimsTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClaimsTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:personIdentifier"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:personName"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:latinName"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:birthName"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:email"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:phone"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:gender"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:dateOfBirth"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:2.0:attributes:placeOfBirth"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:cannonicalName"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:nationalityCode"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:canonicalResidenceAddress"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:adminOID"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:adminLegalIdentifier"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:admLegalName"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:admPosition"/>
 *     &lt;enumeration value="urn:egov:bg:eauth:1.0:attributes:admUnit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ClaimsTypeEnum")
@XmlEnum
public enum ClaimsTypeEnum {

    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:personIdentifier")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_PERSON_IDENTIFIER("urn:egov:bg:eauth:2.0:attributes:personIdentifier"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:personName")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_PERSON_NAME("urn:egov:bg:eauth:2.0:attributes:personName"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:latinName")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_LATIN_NAME("urn:egov:bg:eauth:2.0:attributes:latinName"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:birthName")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_BIRTH_NAME("urn:egov:bg:eauth:2.0:attributes:birthName"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:email")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_EMAIL("urn:egov:bg:eauth:2.0:attributes:email"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:phone")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_PHONE("urn:egov:bg:eauth:2.0:attributes:phone"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:gender")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_GENDER("urn:egov:bg:eauth:2.0:attributes:gender"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:dateOfBirth")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_DATE_OF_BIRTH("urn:egov:bg:eauth:2.0:attributes:dateOfBirth"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:placeOfBirth")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_PLACE_OF_BIRTH("urn:egov:bg:eauth:2.0:attributes:placeOfBirth"),
    @XmlEnumValue("urn:egov:bg:eauth:2.0:attributes:canonicalResidenceAddress")
    URN_EGOV_BG_EAUTH_2_0_ATTRIBUTES_CANONICAL_RESIDENCE_ADDRESS("urn:egov:bg:eauth:2.0:attributes:canonicalResidenceAddress"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:cannonicalName")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_CANNONICAL_NAME("urn:egov:bg:eauth:1.0:attributes:cannonicalName"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:nationalityCode")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_NATIONALITY_CODE("urn:egov:bg:eauth:1.0:attributes:nationalityCode"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:adminOID")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_ADMIN_OID("urn:egov:bg:eauth:1.0:attributes:adminOID"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:adminLegalIdentifier")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_ADMIN_LEGAL_IDENTIFIER("urn:egov:bg:eauth:1.0:attributes:adminLegalIdentifier"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:admLegalName")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_ADM_LEGAL_NAME("urn:egov:bg:eauth:1.0:attributes:admLegalName"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:admPosition")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_ADM_POSITION("urn:egov:bg:eauth:1.0:attributes:admPosition"),
    @XmlEnumValue("urn:egov:bg:eauth:1.0:attributes:admUnit")
    URN_EGOV_BG_EAUTH_1_0_ATTRIBUTES_ADM_UNIT("urn:egov:bg:eauth:1.0:attributes:admUnit");
    private final String value;

    ClaimsTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClaimsTypeEnum fromValue(String v) {
        for (ClaimsTypeEnum c: ClaimsTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
