//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 11:22:01 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:bg:egov:eauth:2.0:saml:ext", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.bulsi.egov.saml.schema;
