//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 11:22:01 AM EEST 
//


package bg.bulsi.egov.saml.schema;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import bg.bulsi.egov.saml.RequestedAttribute;


/**
 * <p>Java class for RequestedAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestedAttributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestedAttribute" type="{urn:bg:egov:eauth:2.0:saml:ext}RequestedAttributeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedAttributesType", propOrder = {
    "requestedAttributes"
})
public class RequestedAttributesType {

    @XmlElement(name = "RequestedAttributes", required = true)
    protected List<RequestedAttribute> requestedAttributes;

	public List<RequestedAttribute> getRequestedAttributes() {
		return requestedAttributes;
	}

	public void setRequestedAttributes(List<RequestedAttribute> requestedAttributes) {
		this.requestedAttributes = requestedAttributes;
	}
   

}
