//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 11:22:01 AM EEST 
//

package bg.bulsi.egov.saml.schema;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import bg.bulsi.egov.saml.AttributeValue;

/**
 * <p>
 * Java class for RequestedAttributesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RequestedAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     	&lt;sequence>
 *        &lt;element name="AttributeValue" type="{urn:bg:egov:eauth:2.0:saml:ext}AttributeValueType"/>
 *     	&lt;sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedAttributeType", propOrder = { "attributeValues" })
@XmlRootElement(name = "RequestedAttributeType")
public class RequestedAttributeType {

	/*
	 * <xsd:attribute name="Name" use="required" type="xsd:string"/> <xsd:attribute
	 * name="NameFormat" use="required" type="xsd:anyURI"/> <xsd:attribute
	 * name="FriendlyName" use="optional" type="xsd:string"/> <xsd:attribute
	 * name="isRequired" use="optional" type="xsd:boolean"/> <xsd:anyAttribute
	 * namespace="##other" processContents="lax"/>
	 */
	@XmlAttribute(name = "Name", required = true)
	protected String name;

	@XmlAttribute(name = "NameFormat", required = true)
	protected String nameFormat;

	@XmlAttribute(name = "FriendlyName")
	protected String friendlyName;

	// @XmlAttribute(name = "isRequired")
	// protected boolean isRequired;

	@XmlElement(name = "AttributeValues", required = true)
	protected List<AttributeValue> attributeValues;

	public List<AttributeValue> getAttributeValues() {
		return attributeValues;
	}

	public void setAttributeValues(List<AttributeValue> attributeValues) {
		this.attributeValues = attributeValues;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameFormat() {
		return nameFormat;
	}

	public void setNameFormat(String nameFormat) {
		this.nameFormat = nameFormat;
	}

	public String getFriendlyName() {
		return friendlyName;
	}

	public void setFriendlyName(String friendlyName) {
		this.friendlyName = friendlyName;
	}
/*
	public boolean isRequired() {
		return isRequired;
	}

	public void setRequired(boolean isRequired) {
		this.isRequired = isRequired;
	}
*/
}
