//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 11:22:01 AM EEST 
//


package bg.bulsi.egov.saml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestedServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestedServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Service" type="{urn:bg:egov:eauth:2.0:saml:ext}ResourceOID"/>
 *         &lt;element name="Provider" type="{urn:bg:egov:eauth:2.0:saml:ext}ResourceOID"/>
 *         &lt;element name="LevelOfAssurance" type="{urn:bg:egov:eauth:2.0:saml:ext}LevelOfAssuranceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedServiceType", propOrder = {
    "service",
    "provider",
    "levelOfAssurance"
})
public class RequestedServiceType {

    @XmlElement(name = "Service", required = true)
    protected String service;
    @XmlElement(name = "Provider", required = true)
    protected String provider;
    @XmlElement(name = "LevelOfAssurance", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String levelOfAssurance;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the levelOfAssurance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelOfAssurance() {
        return levelOfAssurance;
    }

    /**
     * Sets the value of the levelOfAssurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelOfAssurance(String value) {
        this.levelOfAssurance = value;
    }

}
