//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.11 at 10:43:27 PM EET 
//

package soap.clientregix.requests.grao.pna;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.government.regixclient.requests package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PermanentAddressRequest_QNAME = new QName("http://egov.bg/RegiX/GRAO/PNA/PermanentAddressRequest", "PermanentAddressRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.government.regixclient.requests
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PermanentAddressRequest }
     * 
     */
    public PermanentAddressRequest createPermanentAddressRequestType() {
        return new PermanentAddressRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermanentAddressRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/GRAO/PNA/PermanentAddressRequest", name = "PermanentAddressRequest")
    public JAXBElement<PermanentAddressRequest> createPermanentAddressRequest(PermanentAddressRequest value) {
        return new JAXBElement<PermanentAddressRequest>(_PermanentAddressRequest_QNAME, PermanentAddressRequest.class, null, value);
    }

}
