//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.11 at 10:43:27 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://egov.bg/RegiX/GRAO/PNA/PermanentAddressRequest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.clientregix.requests.grao.pna;
