import {NgModule} from '@angular/core';
import {
	MatButtonModule,
	MatCheckboxModule,
	MatFormFieldModule,
	MatIconModule,
	MatInputModule,
	MatSelectModule,
	MatStepperModule,
	MatPaginatorModule,
	MatMenuModule,
	MatCardModule,
	MatRadioModule,
	MatDividerModule,
	MatTableModule,
	MatDialogModule,
	MatAutocompleteModule,
	MatDatepickerModule,
	MatGridListModule,
	MatChipsModule,
	MatTabsModule,
	MatProgressSpinnerModule,
	MatTooltipModule,
	MatExpansionModule,
	MatListModule,
	MatSlideToggleModule,
	MatSortModule,
} from '@angular/material';

@NgModule({
	imports: [
		MatIconModule,
		MatInputModule,
		MatButtonModule,
		MatFormFieldModule,
		MatSelectModule,
		MatStepperModule,
		MatPaginatorModule,
		MatMenuModule,
		MatCardModule,
		MatRadioModule,
		MatDividerModule,
		MatTableModule,
		MatCheckboxModule,
		MatDialogModule,
		MatAutocompleteModule,
		MatDatepickerModule,
		MatGridListModule,
		MatChipsModule,
		MatTabsModule,
		MatTooltipModule,
		MatSortModule,
	],
	exports: [
		MatIconModule,
		MatInputModule,
		MatButtonModule,
		MatFormFieldModule,
		MatSelectModule,
		MatStepperModule,
		MatPaginatorModule,
		MatMenuModule,
		MatCardModule,
		MatRadioModule,
		MatDividerModule,
		MatTableModule,
		MatCheckboxModule,
		MatDialogModule,
		MatAutocompleteModule,
		MatDatepickerModule,
		MatGridListModule,
		MatChipsModule,
		MatTabsModule,
		MatProgressSpinnerModule,
		MatTooltipModule,
		MatExpansionModule,
		MatListModule,
		MatSlideToggleModule,
		MatSortModule,
	],
	providers: [],
})
export class SharedMaterialModule {
}
