export const environment = {
	production: true,
	hmr: false,
	// apiEndpoint: '/api/',
	apiUrl: 'https://eauth-test.egov.bg/tfauthbe/api/',
	url: 'https://eauth-test.egov.bg/tfauthbe/',
	qesUrl: 'https://qes-login.eauth-test.egov.bg',
	cancelAuthEndpoint: '/tfauthbe/api/idp/cancel-auth',
	serviceProvider1Url: 'https://eauth-test.egov.bg/test-sp-low',
	serviceProvider2Url: 'https://eauth-test.egov.bg/test-sp-substaintial',
	serviceProvider3Url: 'https://eauth-test.egov.bg/test-sp-high',
	loginEndpoint: '/tfauthbe/api/idp/login',
	verifyUrl: '/tfauthbe/api/idp/verify-tfa',
	profileUrl: '/profilebe',
	invalidateSSO: 'https://eauth-test.egov.bg/tfauthbe/logout',
	napPikURL: '/tfauthbe/napeid-pik'
	// apiUrl: 'https://eauth.egov.bg/tfauthbe/api/',
	// url: 'https://eauth.egov.bg/tfauthbe/',
	// qesUrl: 'https://qes-login.eauth.egov.bg',
	// cancelAuthEndpoint: '/tfauthbe/api/idp/cancel-auth',
	// serviceProvider1Url: 'https://eauth.egov.bg/test-sp-low',
	// serviceProvider2Url: 'https://eauth.egov.bg/test-sp-substaintial',
	// serviceProvider3Url: 'https://eauth.egov.bg/test-sp-high',
	// loginEndpoint: '/tfauthbe/api/idp/login',
	// verifyUrl: '/tfauthbe/api/idp/verify-tfa',
	// profileUrl: 'https://eauth.egov.bg/profilebe',
	// invalidateSSO: 'https://eauth.egov.bg/tfauthbe/logout'
};
