//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 11:48:44 PM EEST 
//


package soap.clientregix.requests.av.tr;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.government.regixclient.requests.av package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidUICRequest_QNAME = new QName("http://egov.bg/RegiX/AV/TR/ValidUICRequest", "ValidUICRequest");
    private final static QName _ActualStateResponse_QNAME = new QName("http://egov.bg/RegiX/AV/TR/ActualStateResponse", "ActualStateResponse");
    private final static QName _TestStatusType_QNAME = new QName("http://egov.bg/RegiX/AV/TR", "TestStatusType");
    private final static QName _ValidEIKRequest_QNAME = new QName("http://egov.bg/RegiX/AV/TR/ValidEIKRequest", "ValidEIKRequest");
    private final static QName _SearchParticipationInCompaniesRequest_QNAME = new QName("http://egov.bg/RegiX/AV/TR/SearchParticipationInCompaniesRequest", "SearchParticipationInCompaniesRequest");
    private final static QName _ActualStateRequest_QNAME = new QName("http://egov.bg/RegiX/AV/TR/ActualStateRequest", "ActualStateRequest");
    private final static QName _ValidUICResponse_QNAME = new QName("http://egov.bg/RegiX/AV/TR/ValidUICResponse", "ValidUICResponse");
    private final static QName _ValidEIKResponse_QNAME = new QName("http://egov.bg/RegiX/AV/TR/ValidEIKResponse", "ValidEIKResponse");
    private final static QName _SearchParticipationInCompaniesResponse_QNAME = new QName("http://egov.bg/RegiX/AV/TR/SearchParticipationInCompaniesResponse", "SearchParticipationInCompaniesResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.government.regixclient.requests.av
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompanyParticipationType }
     * 
     */
    public CompanyParticipationType createCompanyParticipationType() {
        return new CompanyParticipationType();
    }

    /**
     * Create an instance of {@link DetailsType }
     * 
     */
    public DetailsType createDetailsType() {
        return new DetailsType();
    }

    /**
     * Create an instance of {@link NonMonetaryDepositType }
     * 
     */
    public NonMonetaryDepositType createNonMonetaryDepositType() {
        return new NonMonetaryDepositType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link MandateType }
     * 
     */
    public MandateType createMandateType() {
        return new MandateType();
    }

    /**
     * Create an instance of {@link AddemptionOfTraderType }
     * 
     */
    public AddemptionOfTraderType createAddemptionOfTraderType() {
        return new AddemptionOfTraderType();
    }

    /**
     * Create an instance of {@link SubjectOfActivityType }
     * 
     */
    public SubjectOfActivityType createSubjectOfActivityType() {
        return new SubjectOfActivityType();
    }

    /**
     * Create an instance of {@link Persons }
     * 
     */
    public Persons createPersons() {
        return new Persons();
    }

    /**
     * Create an instance of {@link ContactsType }
     * 
     */
    public ContactsType createContactsType() {
        return new ContactsType();
    }

    /**
     * Create an instance of {@link LegalFormType }
     * 
     */
    public LegalFormType createLegalFormType() {
        return new LegalFormType();
    }

    /**
     * Create an instance of {@link CapitalAmountType }
     * 
     */
    public CapitalAmountType createCapitalAmountType() {
        return new CapitalAmountType();
    }

    /**
     * Create an instance of {@link NonMonetaryDepositsType }
     * 
     */
    public NonMonetaryDepositsType createNonMonetaryDepositsType() {
        return new NonMonetaryDepositsType();
    }

    /**
     * Create an instance of {@link SeatType }
     * 
     */
    public SeatType createSeatType() {
        return new SeatType();
    }

    /**
     * Create an instance of {@link PersonInformationType }
     * 
     */
    public PersonInformationType createPersonInformationType() {
        return new PersonInformationType();
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link SharesType }
     * 
     */
    public SharesType createSharesType() {
        return new SharesType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ShareType }
     * 
     */
    public ShareType createShareType() {
        return new ShareType();
    }

    /**
     * Create an instance of {@link FieldsType }
     * 
     */
    public FieldsType createFieldsType() {
        return new FieldsType();
    }

    /**
     * Create an instance of {@link NKIDType }
     * 
     */
    public NKIDType createNKIDType() {
        return new NKIDType();
    }

    /**
     * Create an instance of {@link ActualStateRequestType }
     * 
     */
    public ActualStateRequestType createActualStateRequestType() {
        return new ActualStateRequestType();
    }

    /**
     * Create an instance of {@link ActualStateResponseType }
     * 
     */
    public ActualStateResponseType createActualStateResponseType() {
        return new ActualStateResponseType();
    }

    /**
     * Create an instance of {@link SearchParticipationInCompaniesRequestType }
     * 
     */
    public SearchParticipationInCompaniesRequestType createSearchParticipationInCompaniesRequestType() {
        return new SearchParticipationInCompaniesRequestType();
    }

    /**
     * Create an instance of {@link SearchParticipationInCompaniesResponseType }
     * 
     */
    public SearchParticipationInCompaniesResponseType createSearchParticipationInCompaniesResponseType() {
        return new SearchParticipationInCompaniesResponseType();
    }

    /**
     * Create an instance of {@link ValidEIKRequestType }
     * 
     */
    public ValidEIKRequestType createValidEIKRequestType() {
        return new ValidEIKRequestType();
    }

    /**
     * Create an instance of {@link ValidEIKResponseType }
     * 
     */
    public ValidEIKResponseType createValidEIKResponseType() {
        return new ValidEIKResponseType();
    }

    /**
     * Create an instance of {@link ValidUICRequestType }
     * 
     */
    public ValidUICRequestType createValidUICRequestType() {
        return new ValidUICRequestType();
    }

    /**
     * Create an instance of {@link ValidUICResponseType }
     * 
     */
    public ValidUICResponseType createValidUICResponseType() {
        return new ValidUICResponseType();
    }

    /**
     * Create an instance of {@link CompanyParticipationType.Company }
     * 
     */
    public CompanyParticipationType.Company createCompanyParticipationTypeCompany() {
        return new CompanyParticipationType.Company();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidUICRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/ValidUICRequest", name = "ValidUICRequest")
    public JAXBElement<ValidUICRequestType> createValidUICRequest(ValidUICRequestType value) {
        return new JAXBElement<ValidUICRequestType>(_ValidUICRequest_QNAME, ValidUICRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualStateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/ActualStateResponse", name = "ActualStateResponse")
    public JAXBElement<ActualStateResponseType> createActualStateResponse(ActualStateResponseType value) {
        return new JAXBElement<ActualStateResponseType>(_ActualStateResponse_QNAME, ActualStateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR", name = "TestStatusType")
    public JAXBElement<StatusType> createTestStatusType(StatusType value) {
        return new JAXBElement<StatusType>(_TestStatusType_QNAME, StatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidEIKRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/ValidEIKRequest", name = "ValidEIKRequest")
    public JAXBElement<ValidEIKRequestType> createValidEIKRequest(ValidEIKRequestType value) {
        return new JAXBElement<ValidEIKRequestType>(_ValidEIKRequest_QNAME, ValidEIKRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchParticipationInCompaniesRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/SearchParticipationInCompaniesRequest", name = "SearchParticipationInCompaniesRequest")
    public JAXBElement<SearchParticipationInCompaniesRequestType> createSearchParticipationInCompaniesRequest(SearchParticipationInCompaniesRequestType value) {
        return new JAXBElement<SearchParticipationInCompaniesRequestType>(_SearchParticipationInCompaniesRequest_QNAME, SearchParticipationInCompaniesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualStateRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/ActualStateRequest", name = "ActualStateRequest")
    public JAXBElement<ActualStateRequestType> createActualStateRequest(ActualStateRequestType value) {
        return new JAXBElement<ActualStateRequestType>(_ActualStateRequest_QNAME, ActualStateRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidUICResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/ValidUICResponse", name = "ValidUICResponse")
    public JAXBElement<ValidUICResponseType> createValidUICResponse(ValidUICResponseType value) {
        return new JAXBElement<ValidUICResponseType>(_ValidUICResponse_QNAME, ValidUICResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidEIKResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/ValidEIKResponse", name = "ValidEIKResponse")
    public JAXBElement<ValidEIKResponseType> createValidEIKResponse(ValidEIKResponseType value) {
        return new JAXBElement<ValidEIKResponseType>(_ValidEIKResponse_QNAME, ValidEIKResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchParticipationInCompaniesResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://egov.bg/RegiX/AV/TR/SearchParticipationInCompaniesResponse", name = "SearchParticipationInCompaniesResponse")
    public JAXBElement<SearchParticipationInCompaniesResponseType> createSearchParticipationInCompaniesResponse(SearchParticipationInCompaniesResponseType value) {
        return new JAXBElement<SearchParticipationInCompaniesResponseType>(_SearchParticipationInCompaniesResponse_QNAME, SearchParticipationInCompaniesResponseType.class, null, value);
    }

}
