//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 11:48:44 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://egov.bg/RegiX/AV/TR", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.clientregix.requests.av.tr;
