//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 11:48:44 PM EEST 
//


package soap.clientregix.requests.av.tr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Indent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndentType" type="{http://egov.bg/RegiX/AV/TR}IndentTypeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectType", propOrder = {
    "indent",
    "name",
    "indentType"
})
public class SubjectType {

    @XmlElement(name = "Indent")
    protected String indent;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "IndentType")
    protected IndentTypeType indentType;

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndent() {
        return indent;
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndent(String value) {
        this.indent = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the indentType property.
     * 
     * @return
     *     possible object is
     *     {@link IndentTypeType }
     *     
     */
    public IndentTypeType getIndentType() {
        return indentType;
    }

    /**
     * Sets the value of the indentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndentTypeType }
     *     
     */
    public void setIndentType(IndentTypeType value) {
        this.indentType = value;
    }

}
