###########################################################
# 3rd party Service Providers -> SpProvidersConfiguration
###########################################################

sp.3rd.party:
   providers: 
      'test': 
         entity-id: 'test'
         name: 
            'bg': 'СП 1'
            'en': 'SP 1'
         binding-url: "https://xxx.com"
         
       
   