###########################################################
# Identity Provider -> IdpConfigurationProperties
###########################################################

idp:
  #
  entity_id: https://eauth-test.egov.bg
  # Private key used to sign the SAML response
  #private_key: certificates/private.key
  private_key: certificates/egov-bg.key
  # Public certificate to verify the signature of the SAML response
  #certificate: certificates/certificate.crt
  certificate: certificates/egov-bg.pem
  # Passphrase of the keystore
  passphrase: secret  
  # base url
  base_url: https://eauth-test.egov.bg
  # backend context for failure handlers url
  path_prefix: /tfauthbe
  # The number of seconds before a lower time bound, or after an upper time bound, to consider still acceptable
  clock_skew: 300
  # Number of seconds after a message issue instant after which the message is considered expired
  expires: 300
  # Authentication method ALL for every username / password combination and USER for the configured users
  auth_method: ALL
  # Are endpoints compared. If so then pay notice to the base_url when behind a load balancer
  compare_endpoints: true
  # Organization Info
  organization_data:
     name: DAEU
     display_name: State e-Government Agency
     url: https://e-gov.bg
  support_contact:   
     email: knivanov@e-gov.bg
     company: E-GOV
     given_name: Krasimir
     sur_name: Ivanov
     phone:
  technical_contact:   
     email: strahil.vitkov@bul-si.bg
     company: BUL SI
     given_name: Strahil
     sur_name: Vitkov
     phone:

  # Claims XSD /eauth-saml-extensions/src/main/resources/schema/bg-egov-eauthentication-2.0.xsd
  claims: /home/gdimitrov/workspaces201909/eAuth2/egov-eauth/eauth-common-libs/eauth-saml-extensions/src/main/resources/schema/bg-egov-eauthentication-2.0.xsd
  #
  needsSigning: false
  # SignatureConstants.ALGO_ID_SIGNATURE_RSA_SHA256 
  default_signature_algorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
  # 
  signature_algorithm: 
  #
  sp_type: 
  # Set<String> 
  digest_methods: !!set
     ? 'http://www.w3.org/2001/04/xmlenc#sha256'
  # Set<String> 
  signing_methods: !!set
     ? 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
  # Set<String> 
  encryption_algorithms: !!set
     ? alg1
  # transient HashMap<String, String> 
  protocolBindingLocation: 
     'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST': 'https://eauth-test.egov.bg/SingleSignOnService'
  #
  levelOfAssurance: 
     - LOW
     - SUBSTANTIAL
     - HIGH
  #
  hide_loa_type: false
  #
  eauth_protocol_version: 2.0.0
  # 
  eauth_assertion_attributes: 
     - urn:egov:bg:eauth:2.0:attributes:personIdentifier
     - urn:egov:bg:eauth:2.0:attributes:personName
     - urn:egov:bg:eauth:2.0:attributes:email
     - urn:egov:bg:eauth:2.0:attributes:phone
     - urn:egov:bg:eauth:2.0:attributes:latinName
     - urn:egov:bg:eauth:2.0:attributes:birthName
     - urn:egov:bg:eauth:2.0:attributes:dateOfBirth
     - urn:egov:bg:eauth:2.0:attributes:gender
     - urn:egov:bg:eauth:2.0:attributes:placeOfBirth
     - urn:egov:bg:eauth:1.0:attributes:canonicalResidenceAddress
  # Map<String, List<String>>
  attributes:
     'key1':
        - listValue
        - listValue2
  # List<FederatedUserAuthenticationToken> users             ::IdpConfigurationProperties
  # private Map<String, List<String>> attributes             ::FederatedUserAuthenticationToken
  #	!!! constructor required private final Object principal                           ::UsernamePasswordAuthenticationToken
  #	!!! constructor required private Object credentials                               ::UsernamePasswordAuthenticationToken
  # !!! constructor required private final Collection<GrantedAuthority> authorities   ::AbstractAuthenticationToken
  #	private Object details                                   ::AbstractAuthenticationToken
  #	private boolean authenticated = false                    ::AbstractAuthenticationToken
  #users:
  #   attributes:
  #      -
  #         'keyX1': 
  #            - list1
  #            - list2
  #acs_endpoint: http://www
  
  