#################################################################################################
# 3rd party Identity Providers -> EidProvidersConfiguration
#
# loa: LOW, SUBSTANTIAL, HIGH;
# eid-processs: POLLING, CALLBACK;
# type: DEFAULT, EGN, PASS, IDCARD, EIK, EMAIL, DIGITS, PHONE, LENGTH20, SECRET;
# e-id: IDENTITY, PASSWORD,	ADDITIONAL;
# provider_id: correspons to vendor_id in the underling;
# attributes: ID RULE: 
#  IdentityParam.provider_id + "_" + ProviderIdSuffix.name(){USERNAME, PASSWORD, EGN, PIK, PUK};
# expirationPeriod: [sec]
#################################################################################################

idp.3rd.party:
   providers: 
      'test_provider': 
         provider-id: 'test_provider'
         provider-api-key: 'vendor_id'
         name: 
            'bg': '1 НИСКО (тест)'
            'en': '1 LOW (test)'
         loa: LOW
         eid-processs: POLLING
         eid-callback-url: ''
         tfa-required: false
         active: true
         expirationPeriod: 60
         eid-provider-connection:
            endpoint: 'http://localhost:8230/exIdent'
            client-ssl-required: false
            client-key-store:
               alias: 
               path: 
               type: 
               pass: 
            tls-version: ''
            custom-headers:
               'vendor-id': 
               'relying-party-id': 
         attributes:
            'test_provider_USERNAME':
               id: 'username'
               mandatory: true
               label: {
                  'bg':'Потребител',
                  'en':'User'
               }
               type: DEFAULT
               e-id: IDENTITY
            'test_provider_PASSWORD':
               id: 'password'
               mandatory: true
               label:  {
                  'bg':'Парола',
                  'en':'Password'
               } 
               type: SECRET
               e-id: PASSWORD
      'sub_test': 
         provider-id: 'sub_test'
         provider-api-key: 'vendor_id'
         name: 
            'bg': '2 Съществено (LOW+2FA) (тест)'
            'en': '2 SUBSTANTIAL (LOW+2FA) (test)'
         loa: SUBSTANTIAL
         eid-processs: POLLING
         eid-callback-url: ''
         tfa-required: true
         active: true
         expirationPeriod: 60
         eid-provider-connection:
            endpoint: 'http://localhost:8230/exIdent'
            client-ssl-required: false
            client-key-store:
               alias: 
               path: 
               type: 
               pass: 
            tls-version: ''
            custom-headers:
               'vendor-id': 
               'relying-party-id': 
         attributes:
            'test_provider_USERNAME':
               id: 'username'
               mandatory: true
               label: {
                  'bg':'Потребител',
                  'en':'User'
               }
               type: DEFAULT
               e-id: IDENTITY
            'test_provider_PASSWORD':
               id: 'password'
               mandatory: true
               label:  {
                  'bg':'Парола',
                  'en':'Password'
               }
               type: SECRET
               e-id: PASSWORD
      'nap_pik': 
         provider-id: 'nap_pik'
         provider-api-key: 'vendor_id'
         name: 
            'bg': 'Вход с ПИК на НАП (тест)'
            'en': 'Login with NRA PIC (test)'
         loa: LOW
         eid-processs: CALLBACK
         eid-callback-url: ''
         tfa-required: false
         active: true
         expirationPeriod: 60
         eid-provider-connection:
            endpoint: ''
            client-ssl-required: false
            client-key-store:
               alias: 
               path: 
               type: 
               pass: 
            tls-version: ''
            custom-headers:
               'vendor-id': 
               'relying-party-id': 
      'nap_pik_tfa': 
         provider-id: 'nap_pik_tfa'
         provider-api-key: 'vendor_id'
         name: 
            'bg': 'Вход с ПИК на НАП (LOW + 2FA) (тест)'
            'en': 'Login with NRA PIC (LOW + 2FA) (test)'
         loa: LOW
         eid-processs: CALLBACK
         eid-callback-url: ''
         tfa-required: true
         active: true
         expirationPeriod: 60
         eid-provider-connection:
            endpoint: ''
            client-ssl-required: false
            client-key-store:
               alias: 
               path: 
               type: 
               pass: 
            tls-version: ''
            custom-headers:
               'vendor-id': 
               'relying-party-id':
      'qes': 
         provider-id: 'qes'
         provider-api-key: 'vendor_id'
         name: 
            'bg': '3 ВИСОКО КЕП'
            'en': '3 HIGH QES'
         loa: HIGH
         eid-processs: POLLING
         eid-callback-url: ''
         tfa-required: false
         active: true
         expirationPeriod: 60
         eid-provider-connection:
            endpoint: ''
            client-ssl-required: false
            client-key-store:
               alias: 
               path: 
               type: 
               pass: 
            tls-version: 1.3
            custom-headers:
               'vendor-id': 
               'relying-party-id': 
      'evrotrust_CQES_test':
         provider-id: 'evrotrust_CQES_test'
         provider-api-key: 'provider_id'
         name: 
            'bg': '5 Евротръст Облачен КЕП (тест)'
            'en': '5 Evrotrust Cloud QES (test)'
         loa: HIGH
         eid-processs: POLLING
         eid-callback-url: ''
         tfa-required: false
         active: true
         expirationPeriod: 120
         eid-provider-connection:
            endpoint: 'https://testeauth.evrotrust.com/exIdent'
            client-ssl-required: false
            client-key-store:
               alias: eauth 
               path: 'classpath:certificates/evrotrust/eauth1.0_cqes.jks'
               type: 'JKS'
               pass: '1234'
            tls-version: 1.2
            custom-headers:
               'VENDOR_ID': 'evrotrust_CQES_test'
               'relyingPartyId': 43210987
         attributes:
            'evrotrust_EGN':
               id: 'evrotrust_EGN'
               mandatory: true
               label: {
                  'bg': 'ЕГН',
                  'en': 'ENG'
               }
               type: EGN
               e-id: IDENTITY
      'borica_CQES_test':
         provider-id: 'borica_CQES_test'
         provider-api-key: 'provider_id'
         name: 
            'bg': '4 Борика Облачен КЕП (тест)'
            'en': '4 Borica Cloud QES (test)'
         loa: HIGH
         eid-processs: POLLING
         eid-callback-url: ''
         tfa-required: false
         active: true
         expirationPeriod: 120
         eid-provider-connection:
            endpoint: 'https://cqes-rptest.b-trust.bg/signing-api/v2/exIdent/eAuth2'
            client-ssl-required: true
            client-key-store:
               alias: borica-test 
               path: 'classpath:certificates/borica-test/eauthn-cqes-bg.jks'
               type: 'JKS'
               pass: '1234'
            tls-version: 1.2
            custom-headers:
               'VENDOR_ID': 'Borica Cloud QES'
               'relyingPartyId': 436554
         attributes:
            'borica_EGN':
               id: 'borica_EGN'
               mandatory: true
               label: {
                  'bg': '',
                  'en': ''
               }
               type: EGN
               e-id: IDENTITY
      'borica_CQES': 
         provider-id: 'borica_CQES'
         provider-api-key: 'provider_id'
         name: 
            'bg': 'Борика Облачен КЕП'
            'en': 'Borica Cloud QES'
         loa: HIGH
         eid-processs: POLLING
         eid-callback-url: ''
         tfa-required: false
         active: true
         expirationPeriod: 120
         eid-provider-connection:
            endpoint: 'https://cqes-rp.b-trust.bg/signing-api/v2/exIdent/eAuth2'
            client-ssl-required: true
            client-key-store:
               alias: borica
               path: 'classpath:certificates/borica/eauthn-cqes-bg.jks'
               type: 'JKS'
               pass: '1234'
            tls-version: 1.2
            custom-headers:
               'VENDOR_ID': 'Borica Cloud QES'
               'relyingPartyId': 675832821
         attributes:
            'borica_CQES_EGN':
               id: 'borica_CQES_EGN'
               mandatory: true
               label: {
                  'bg': 'ЕГН',
                  'en': 'EGN'
               }
               type: EGN
               e-id: IDENTITY            