server:
   port: 8080
#   session-timeout: 1800
   ssl:
      enabled: false
#     key-store-type: 
#     key-store: 
#     key-store-password: 
#     key-password:
      trust-store-type: JKS
      trust-store: 'classpath:certificates/idptruststore.jks'
      trust-store-password: 1234
#      trust-password: 
#   http:
#      port: 
   servlet:
      session:
      # 8 hours before we time-out
         timeout: 28800
         cookie:
            secure: false
   tomcat:
      remoteip:
         protocol-header: x-forwarded-proto
         remoteIpHeader: x-forwarded-for
   error:
      path: '/error'
      whitelabel:
         enabled: false

spring:
   application:
      name: eAuth_IdP
   profiles:
      #activate test if exist [application-test.yml]
      #or --- "spring.profiles: test" paragraph
      #instantiate annotation @Profile("test")
      active: dev #dev | prod
      include: idp, sp, idp-config, actuator
   datasource:
      url: 'jdbc:postgresql://eauth2-db.egov.bg:5432/eauth'
      username: bulsiadmin
      password: bulsivirtual
      driver-class-name: org.postgresql.Driver
      sql-script-encoding: UTF-8

   jpa:
      database: postgresql
      hibernate:
         use-new-id-generator-mappings: true
         ddl-auto: update
      properties:
         hibernate:
            show_sql: true
            dialect: org.hibernate.dialect.PostgreSQL94Dialect
          #default_schema: profile
      show-sql: true

   session:
      store-type: hazelcast
      hazelcast:
         flush-mode: immediate
   devtools:
      restart:
         enabled: true
# ---------------------------------------------------------------------
## thymeleaf
# ---------------------------------------------------------------------
   thymeleaf:
      encoding: UTF-8
      mode: HTML
      suffix: .html
      prefix: classpath:/templates/

eauth:
   security:
      jwt:
         token-secret: 9B728DEAEA5411628AAD8E7426D1A
         token-expiration-msec: 300000
      provider:
         id-secret: NWKNjXLRdRNjhjgTcRssMmMskbxFrRJWvjWMw7wbVCcHJxKtvf74KzrJRg4hfFhj

# //TODO HARDCODED
# SAML AuthnRequest validator
validate:
   authn:
      oids: false
      claims: true

# UserService 2FA login identfiers
tfa:
   login:
      identifiers:
         - 1010101010
         - 3702134041
         - 6212299283
         - 1809113164
         - 4110253049
         - 9501265816
         - 5905245899
         - 5111103277
         - 7805153318
         - 2902284392
         - 8805248360
         - 8209048959
         - 6912188979
         - 7806277020 # Страхо  
         - 5507157663 # Стойчо Чичеков
         - 7302105283 # Красимир Иванов
         - 8608126455 # Таня Петрова
         - 8007276274 # Вергиния Стоименова
         - 8002106510 # Ева Бончева
         - 6608065340 # Свилен ДАЕУ
         - 5807026290 # Дими

nap.provider:
   id: 'nap_pik'
   identity:
      type: egn
      default-name: 'Потребител идентифициран с ПИК на НАП'
      endpoint: 
         url: 'https://inetdec.nra.bg/pls/pub/login.auth?method=pic' #&sysid={org1} #>>https://org1.bg/?jwt=Ey53..
         unique_system_id:
            name: sysid
            value: PIK_DAEU_TEST
            key: 3rnBsq6vwDJOM6BkJEVGwCGayOoH6mWL #32bit jwt signature 
      redirect:
         url: 'https://eauth-test.egov.bg/tfauthbe/napeid/' #localhost: 'http://eauth-test.egov.bg:8080/napeid/'
         jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJOUkEiLCJleHAiOjE0MTcwNzE3MjMzNjEsInR5IjowLCJpZCI6IjgxMDEwNTU5MDAifQ.JYFZ--KYyX8zLLeIfJswTOBEKcY7oMq8Br5P76LDKIQ' #test
   vendor:
      id: vid
      key: vk
         
---
spring:
   profiles: dev
   logging:
      config: classpath:logback.xml
      level:
         org:
            apache:
               http: DEBUG
            springframework:
               security: DEBUG
               web:
                 servlet:
                    mvc:
                      method:
                        annotation: TRACE
            thymeleaf: TRACE
---
spring:
   profiles: prod
# The logging configuration. On a real server this will be a file url. e.g. file://{{ mujina_dir }}/logback.xml
   logging:
      path: log
      file: ${logging.path}/eauth-ui.log
      config: classpath:logback.xml
      level:
         org:
            apache:
               http: DEBUG
            springframework:
               security: DEBUG
            thymeleaf: TRACE
